### ISSUE TITLE
Just a suggestion for that clock singleton class in your code

### ISSUE THREAD

**Issue by slidenerd** [Flippo24/candles#1]
First of all, amazing work, I have seen the original repo and I saw your improvements too, making it generic for multiple pairs was way to go :) at this moment, the code has only one bug, clock wont be a singleton if accessed from different directory paths which is explained more in detail [HERE](https://derickbailey.com/2016/03/09/creating-a-true-singleton-in-node-js-with-es6-symbols/). might wanna consider incorporating those changes! Fantastic work

**Comment by Flippo24** [comment]
Thanks for your feedback. If I look at the clock now, then a singleton makes no sense. The clock may differ depending on the provider and settings for timediff. So i need an own instance for each Provider (maybe each pair, depending on provider and latency). In my opinion, I can delete the getInstance function. Maybe I understood the singleton stuff wrong and you get me on the right path.
