### ISSUE TITLE
First candle not valid

### ISSUE THREAD

**Issue by ntftrader** [Flippo24/candles#2]
Candlestick constructor do not set ohlc values correctly leaving the first candle with 0, null or NaN values.

updatePrice should then check for and correct those ohlc values so the first candle is a valid one.

**Comment by ntftrader** [comment]
Also, `.toFixed` - formatting should probably be best done somewhere else?

**Comment by Flippo24** [comment]
Can you give me an example when the first candle is invalid? The first candles will be dropped until an open price will be set and candle is recorded in about a timeframe. So candles without missing ticks at startup shouldn't pushed to the series. Have a look at _Series.closeSeriesCandle()_.

The .toFixed is done cause of the [IEEE754](https://www.youtube.com/watch?v=wPBjd-vb9eI). User expexted 0.1 + 0.2 = 0.3 not 0.30000000000000004. Sure i can do this with decimal.js, but i like to have the prices in plain Number formating. Does the unary_plus help me with this?
