### ISSUE TITLE
Preload data

### ISSUE THREAD

**Issue by ntftrader** [Flippo24/candles#3]
Feature request: It would be extremely useful to prepopulate candles from historical trades/ticks and then overlap with live trade/tick data.

**Comment by Flippo24** [comment]
I have thought about it, but have not found a working solution in which it works seamlessly. Then I stuck with it that it should be easier to use a suitable database like influxdb for it. It would also make candles unnecessary. How would you implement it?

**Comment by ntftrader** [comment]
I would keep it as is, free of dependencies and just handle trades/ticks as they come which is the strength of this module!

Noramally one asks for both initial data (historical) and subscribe to new data at the same time. On a socket you really do not know which will be first. If the module has a (pre-)populate and keeps track of last (timestamp) then this could give a seemless handling of initial and continous data.

**Comment by ntftrader** [comment]
So if it just keeps track of start time for initial and first live data then all candles can be populated in between.

**Comment by Flippo24** [comment]
How to deal with missing ticks? If e.g. the program is restarted or the network fails for some time?

**Comment by ntftrader** [comment]
That should be handled outside this module, and missing ticks should be regarded as non existing hence forward filling with last known close value
