### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by PraneshASP** [Flippo24/candles#5]
Hi,

How the memory is managed in this project? Are the candles get cleared whenever the timeframe is completed or it will remain in memory? if it remains in memory how do I make changes in the server, as everything in memory will be lost once I restart the server right?

**Comment by Flippo24** [comment]
Every time a the currentCandle is closed, this currentCandle is added to the candles array. CurrentCandle then become a new Candlestick. The candles array will remain in memory. Have a look in [Series.js](https://github.com/Flippo24/candles/blob/master/src/Series.js)

You can set the lenght of the candles array which you like to hold in memory. See [documentation](https://github.com/Flippo24/candles#addproduct).

On restart everything will be lost. If you like to save the candles, you can use any database you like.
You can use [Events](https://github.com/Flippo24/candles#events) which are triggered on candle open, close and when the currentCandle is updated.

**Comment by PraneshASP** [comment]
Thanks for the instant reply. 

Yes, that's fine I'm using database to persist candles. But is there any method available to generate candlestick from the previous data in case the server gets crashed. For ex., I'm generating 24h candle.. if the server goes down for 2-3 hours, the trade data on that interval will not be included in candle stick data right?

**Comment by Flippo24** [comment]
This is the reason for skipping the fist uncomplete candle. You cant be shure to get all data from the first timeframe and this candle wont represent the correct data. If you server goes down, i think you shoud skip this timeframe and get the last candle from an historical feed of your Exchange to be sure it is correct.

**Comment by PraneshASP** [comment]
Ok. Thanks for your time mate.

Cheers!
