### ISSUE TITLE
Capacity?

### ISSUE THREAD

**Issue by digitalml** [Flippo24/candles#7]
Thanks for the nice work on this library, thank you.. How will this hold up capacity / memory wise if I use this to calc all candles for multiple time frames on 11k symbols simultaneously (1m, 5m, 15m, 1h, 4h, 1d)?

**Comment by Flippo24** [comment]
Thank you.

That depends on how many candles you want to save in the series for each timeframe. You can specify the number with addProduct.
I would worry less about the memory at that point. It is more important to note at this point that the processor load increases with the number of symbols. In the worst case the processing could then lead to shifts in the time stamp. Depending on what you have set.

**Comment by digitalml** [comment]
Thanks for replying so fast. I’d really only need 1 (current). So 11k x 6 time frames = 66k ish Everything else I can store in database and redis. So then maybe not an issue? 

Also my data is delayed by 500ms or so but the candle closes exactly at 00 on the minute. So I’m missing the last trade or two and the close is wrong. I’ve tried using the timediff value to 500 but the candle close event still always fires at 00 ?  Am I wrong that value should delay close time ?

Thanks again for the help.

**Comment by Flippo24** [comment]
At first check your system time. [time.js](https://time.is/) 500ms seams a bit high to me. 
you dont have to set the value timediff. If you enabled it and set fixed to false, then you have to use adjustClock(). So the most accurate closetime will be calculated.

11000 symbols x 6 timeframes x ~60 bytes per candle x 2 (current and last one) = 7.920.000 bytes. I think this is not so much.
